### ISSUE TITLE
step over, does a skip to my loop and steps into

### ISSUE THREAD

**Issue by dalehenrich** [GemTalk/Jadeite#110] opened 2018-08-24 22:06 UTC
execute this:
```smalltalk
[
self halt.
1 printString = 2 printString ] 
	on: Error
	do: [:ignored |
		self error: 'error' ]
```
step over ... expecting to be at one of the printString's ... instead you are in the printString:
```
a Halt occurred (error 2709)
---
SmallInteger >> printString @1 line 1
[] in  Executed Code  @3 line 3
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
Executed Code  @2 line 4
GsNMethod class >> _gsReturnToC @1 line 1
```
for extra credit, clicking on the the second frame gives the following:
![image](https://user-images.githubusercontent.com/623951/44610019-249a2f80-a7af-11e8-86ee-63a65fe41296.png)

**Comment by ericwinger** [comment] 2018-08-31 22:28
@dalehenrich The step into is by design as a workaround to kermit bug #45553. Essentially, the server comes back with a frame that doesn't have the next step point. Instead of throwing an error, the code was setup to do a step into.  Whether that is right or wrong is debatable. 
The server bug is fixed in 3.4. 

Let me know if you can think of an alternative way to handle this error in the Jadeite code, or if you'd like to wait until Rowan supports 3.4.

**Comment by dalehenrich** [comment] 2018-09-01 00:33
Okay ... in tODE, the tODE debugger seems to work as expected:
![image](https://user-images.githubusercontent.com/623951/44940464-9e985e80-ad43-11e8-9150-1cb82b73c38a.png)
and I don't recall putting any special stepping logic into the debugger for this particular case, so perhaps it is worth discussing rather than wait until our customers are able to move to 3.4 ...

**Comment by ericwinger** [comment] 2018-09-02 23:38
@dalehenrich I'll be curious to see what step points you have available at that point. The Jadeite code is currently getting back ``nil`` which isn't easy to step to.

**Comment by dalehenrich** [comment] 2019-01-16 22:55
hit this again .. hit halt point:
![image](https://user-images.githubusercontent.com/623951/51283673-d8d66580-199d-11e9-9e56-0edbc10798d8.png)
after step over - instead of stopping at the extension method, we step into the extension method ... not right:
![image](https://user-images.githubusercontent.com/623951/51283739-03282300-199e-11e9-94df-c359f76c6303.png)
Note that halt is step point 6:
![image](https://user-images.githubusercontent.com/623951/51283885-631ec980-199e-11e9-95fd-3b104bf2ff3c.png)
and #extension is step point 7
![image](https://user-images.githubusercontent.com/623951/51283934-94979500-199e-11e9-994a-b6079c3f0d49.png)

**Comment by LisaAlmarode** [comment] 2019-01-22 05:34
There is something wonky about step points, and I think that's messing up stepping over.  It seems to be a little confused about numbering in blocks vs. methods.  

With the construction

[
self halt.
1 negated = 2 negated ] 
	on: Error
	do: [:ignored |
		self error: 'error' ]

I don't seem to be able to ever get to a place in the debugger where I'm looking at this code and execution is before the inside of the first "negated".   It is always inside Integer >> negated, if I do over or out of, and if I do into and go through the halt it also gets to that place. 

I can get there if I put the code in a method and set a breakpoint.  The negated is step point 5 in the method, but the context says @2.  

![image](https://user-images.githubusercontent.com/13142166/51514285-ef2c5900-1dc3-11e9-98bc-305e41c5c903.png)

Something is amis.

**Comment by LisaAlmarode** [comment] 2022-11-17 00:12
I don't see either of the examples reproducing in 3.2.12, and I'm glad to close this ancient bug.

**Closed by LisaAlmarode** 2022-11-17 00:12 UTC
