### ISSUE TITLE
Debugger step within block and then select block context has bad behavior 

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#166] opened 2018-09-06 23:35 UTC
Same example code and breakpoint as in #134.

If I edit the code but don't save it, and do a step over (the () with the down arrow), then I see am empty source pane.  The top context updates its step point and source line number, but doesn't show anything.

![image](https://user-images.githubusercontent.com/13142166/45190409-b2840a80-b1f2-11e8-9ed4-5914040fef8e.png)

**Comment by ericwinger** [comment] 2018-09-11 15:53
I believe that the blank source got fixed recently as a side effect to another fix. Please verify as I cannot reproduce. 

fyi - I opened a new issue with all the interesting variants of leaving the source pane in an unsaved state. https://github.com/GemTalk/Jadeite/issues/176

**Comment by LisaAlmarode** [comment] 2018-09-14 13:01
This doesn't seem to be related to edits and saves at all... the same scenario in 3.0.35 results in an error "An unknown RowanDebuggerStepPointError has occurred", and happens when I don't have edits.

1. With breakpoint on test in the interesting loop method, execute; breakpoint leaves you with the top context being the block context.
2. Step into (do not copy to clipboard). This brings you into the Cabbage > test method.
3. Select the frame below, which is the block context frame.
See error.

I get another error with the breakpoint in, which is a bit annoying but not technically a bug.

**Comment by ericwinger** [comment] 2018-09-14 19:02
In 3.2.17, stepping and breakpoints have some problems - See kermit bug #45553. 
There was a workaround in when displaying the process frame. If the frame couldn't find it's step point, it would throw an error which was caught and handled when stepping. However, that same code was used when simply selecting another frame. 

When selecting another frame the fix, which I hope is temporary, was to make the error thrown resumable then only resume it if we aren't stepping. Then the resumed code avoids touching the step point and displays the source code. 

While one won't see the step point [in this scenario ](https://github.com/GemTalk/Jadeite/issues/166#issuecomment-421351203) showing the method source is better than a walkback or a dialog error. 

Fixed in 3.0.36.

**Comment by LisaAlmarode** [comment] 2018-09-18 14:17
The behavior in 3.0.38 is still the same, if I do a step into within a block and then click on the block context frame below, I see an error dialog
      Error while processing error: An unknown RowanDebuggerStepPointError has occurred

If I click okay on that and the next breakpoint dialog, I can then click on all the frames in the stack and it displays, but the first time into block context is a bear.

**Comment by ericwinger** [comment] 2018-11-09 22:58
I was able to reproduce the error. The server returns a nil step point from ``GsNMethod>>_stepPointForMeth:ip:`` Work done in kermit bug # #45553 fixes this problem in later server versions.  (See ``GsNMethod>>_debugInfoAccess:at:`` for a little more on the fix)

``RowanDebuggerStepPointError>>isNested`` was added to workaround the problem and gets rid of the unhelpful dialog box walkback. 

I believe that original problem reported in #224 may be fixed with this check in, too. 

Fixed in 3.0.46

**Closed by ericwinger** 2018-11-09 22:58 UTC
Labels: debugger

**Comment by LisaAlmarode** [comment] 2018-11-13 20:54
Looks good.  I might note that with the the block context selected, code has a red border around the select as well as a highlight on the step point... the border implying a breakpoint, which is a little inexplicable. But I think there's a separate bug on highlighting in debugger.
