### ISSUE TITLE
JadeiteProjectBrowserTestCase>>test_saveMethod fails

### ISSUE THREAD

**Issue by jgfoster** [GemTalk/Jadeite#73] opened 2018-08-20 00:32 UTC
I have RowanSample1 as a git checkout:
```
System performOnServer: 'cd $ROWAN_PROJECTS_HOME/RowanSample1; git status'. 
'On branch master
Your branch is up to date with ''origin/master''.

nothing to commit, working tree clean
'
```
The test fails with this error:
```
a UserDefinedError occurred (error 2318), reason:halt, Expected a git repository to present in the directory: '$ROWAN_PROJECTS_HOME/RowanSample1'

UserDefinedError (AbstractException) >> _signalWith: @5 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwPrjCloneTool (Object) >> error: @6 line 7
[] in  ExecBlock1 (RwPrjCloneTool) >> _validateForGitRootPathForSpecification:gitRepoDir:useSsh:ifDone: @4 line 48
UserDefinedError (AbstractException) >> _executeHandler: @3 line 8
UserDefinedError (AbstractException) >> _signalWith: @1 line 1
UserDefinedError (AbstractException) >> signal @2 line 47
RwGitTool (Object) >> error: @6 line 7
[] in  ExecBlock1 (RwGitTool) >> performOnServer:logging: @24 line 21
RwGitTool >> performOnServer:status: @4 line 4
RwGitTool >> performOnServer:logging: @2 line 4
RwPrjCloneTool (RwAbstractTool) >> readlink: @5 line 8
[] in  ExecBlock0 (RwPrjCloneTool) >> _validateForGitRootPathForSpecification:gitRepoDir:useSsh:ifDone: @9 line 31
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
RwPrjCloneTool >> _validateForGitRootPathForSpecification:gitRepoDir:useSsh:ifDone: @39 line 45
RwPrjCloneTool >> cloneSpecification:gitRootPath:useSsh:registerProject: @9 line 11
RwPrjCloneTool >> cloneSpecification:gitRootPath:useSsh: @2 line 3
RwPrjCloneTool >> cloneSpecUrl:gitRootPath:useSsh: @3 line 4
RowanProjectService >> newGitProject:root:useSsh: @4 line 5
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @9 line 11
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1
```

**Comment by ericwinger** [comment] 2018-08-20 01:16
Yes, this is expected for now. If you clone RowanSample1 project from github into your ROWAN_PROJECTS_HOME directory it should work. 

Eventually, I"ll have a better way to create a play project in the test harness.

**Comment by jgfoster** [comment] 2018-08-20 01:36
What would it take to have RowanSample1 cloned into my ROWAN_PROJECTS_HOME directory? More than the following?

System performOnServer: 'cd $ROWAN_PROJECTS_HOME/RowanSample1; git status'. 
'On branch master
Your branch is up to date with ''origin/master''.

nothing to commit, working tree clean'

**Comment by ericwinger** [comment] 2018-08-21 20:30
@jgfoster I'm having trouble cloning the RowanSample1 project automatically for a test. I've opened Rowan issue with a question. https://github.com/dalehenrich/Rowan/issues/336

Right now I do the clone manually to a local directory in ROWAN_PROJECTS_HOME. That can be done on a command line using git clone. Once it's present on disk I think the test will work.

**Comment by jgfoster** [comment] 2018-08-21 21:01
@ericwinger, As mentioned above, "**I have RowanSample1 as a git checkout**". From within GemStone, I can perform a #performOnServer: to see that there is a Git checkout (see both my comments above for this confirmation). I don't need you to clone the repository automatically for a test. I have already done the clone manually; that was done before the initial bug report. The code fails claiming that there isn't a git repository when there is one.

**Comment by ericwinger** [comment] 2018-08-21 21:22
Hmm, I see what you're saying now and this gets into an area I'm not familiar with. It's not inconceivable that it has something to do with the specification file. 

Could you verify that you have a RowanSample1.ston in the location below? 

```

'file:$ROWAN_PROJECTS_HOME/Rowan/samples/RowanSample1.ston'

 RwSimpleProjectSpecification{
        #specName : 'RowanSample1',
        #projectUrl : 'https://github.com/dalehenrich/RowanSample1',
        #platformSpec : {
                'gemstone' : RwGemStoneSpecification {
                        #defaultSymbolDictName : 'SampleSymbolDict',
                        #defaultUseSessionMethodsForExtensions : false }
        },
        #repoSpec : RwGitRepositorySpecification {
                #committish : 'sample',
                #committishType : 'branch'
        },
        #configsPath : 'rowan/configs',
        #repoPath : 'rowan/src',
        #specsPath : 'rowan/specs',
        #comment : 'Sample project to be used as an example project when first getting started with Jadeite and Rowan.'
}

**Comment by dalehenrich** [comment] 2018-08-21 22:16
@jgfoster If you take a look at the RowanSample4/RowanSample2 Rowan tests you can see how I run tests using automatic git checkouts ... there is an area reserved in the Rowan checkout for stashing git clones and the setup/teardown methods take care of clearing out that directory ...

A common mistake is to not have `$ROWAN_PROJECTS_HOME` set correctly ... anything deeper than that will have to wait until tomorrow or Thursday, since I am still preparing packing files for the candidate release scheduled for tonight ...

**Comment by jgfoster** [comment] 2018-08-22 01:38
@ericwinger, Yes, https://github.com/dalehenrich/Rowan/blob/master/samples/RowanSample1.ston is part of my checkout.

@dalehenrich, Is there any need to do an automatic git checkout? I already have the checkout. As to ```$ROWAN_PROJECTS_HOME```, I tested from within GemStone with the following:
```
System performOnServer: 'cd $ROWAN_PROJECTS_HOME/RowanSample1; git status'.
'On branch master
Your branch is up to date with ''origin/master''.

nothing to commit, working tree clean'
```
It seems to me that this demonstrates that I have a git checkout in the proper location.

**Comment by jgfoster** [comment] 2018-08-22 03:28
Following is the stack for this error:
```
a UserDefinedError occurred (error 2318), reason:halt, Expected a git repository to present in the directory: '$ROWAN_PROJECTS_HOME/RowanSample1'

UserDefinedError (AbstractException) >> _signalWith: @5 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwPrjCloneTool (Object) >> error: @6 line 7
[] in  ExecBlock1 (RwPrjCloneTool) >> _validateForGitRootPathForSpecification:gitRepoDir:useSsh:ifDone: @4 line 48
UserDefinedError (AbstractException) >> _executeHandler: @3 line 8
UserDefinedError (AbstractException) >> _signalWith: @1 line 1
UserDefinedError (AbstractException) >> signal @2 line 47
RwGitTool (Object) >> error: @6 line 7
[] in  ExecBlock1 (RwGitTool) >> performOnServer:logging: @24 line 21
RwGitTool >> performOnServer:status: @4 line 4
RwGitTool >> performOnServer:logging: @2 line 4
RwPrjCloneTool (RwAbstractTool) >> readlink: @5 line 8
[] in  ExecBlock0 (RwPrjCloneTool) >> _validateForGitRootPathForSpecification:gitRepoDir:useSsh:ifDone: @9 line 31
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
RwPrjCloneTool >> _validateForGitRootPathForSpecification:gitRepoDir:useSsh:ifDone: @39 line 45
RwPrjCloneTool >> cloneSpecification:gitRootPath:useSsh:registerProject: @9 line 11
RwPrjCloneTool >> cloneSpecification:gitRootPath:useSsh: @2 line 3
RwPrjCloneTool >> cloneSpecUrl:gitRootPath:useSsh: @3 line 4
RowanProjectService >> newGitProject:root:useSsh: @4 line 5
[] in  ExecBlock1 (JadeServer) >> updateFromSton: @9 line 11
Array (Collection) >> do: @5 line 10
JadeServer64bit32 (JadeServer) >> updateFromSton: @7 line 6
GsNMethod class >> _gsReturnToC @1 line 1
```

**Comment by ericwinger** [comment] 2018-08-23 22:53
@jgfoster James, I noticed that this fails just searching for a test method on the server. 
I don't believe I removed it. Let me know if this is something you were still working on. 

```
a LookupError occurred (error 2021), reason:rtErrKeyNotFound, A reference using the non-existent key #'testMethod' was made into the dictionary RowanFrameService
LookupError (AbstractException) >> _signalWith: @6 line 25
LookupError (AbstractException) >> signal @2 line 47
RowanFrameService class (Object) >> _error:args: @15 line 11
RowanFrameService class (Behavior) >> compiledMethodAt:environmentId: @5 line 9
RowanFrameService class (Behavior) >> compiledMethodAt: @2 line 2
Executed Code  @2 line 1
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by jgfoster** [comment] 2018-08-23 23:05
No, I'm not doing anything on this.

**Comment by dalehenrich** [comment] 2018-08-23 23:15
@jgfoster are you running the server on a mac? And do you happen to have a symbolic link on your path?

I see that `RwPrjCloneTool (RwAbstractTool) >> readlink:` is on the stack, and I'm pretty sure that the Mac version of `readlink` is incompatible with the linux version ... Until I hear differently, I'll assume that both of the answer to my questions above are true and start researching the best way to deal with the Mac ...

**Comment by dalehenrich** [comment] 2018-08-24 00:15
okay if you don't know whether or not you have a sym link or not, then I think we can figure it out by looking at the gem log ... there's a log of output dumped to the gem log, so it would help if you do a `tail -f` on the gem long right before you try doing the clone and then take the output and paste it here so I can look for myself ...

Alternatively, providing with the values of `response` and ``cdResponse` from the 
`_validateForGitRootPathForSpecification:gitRepoDir:useSsh:ifDone:` frame on lline 31:
![image](https://user-images.githubusercontent.com/623951/44558199-acbcfe00-a6f7-11e8-8a0f-0fe27e4fbf40.png)
I also would like the value of the arg to the `readLink:` call that is on the stack ...

**Comment by jgfoster** [comment] 2018-08-24 00:33
When I try to run the test in the title of this issue I get an error that the test resources are not available:

<img width="983" alt="screen shot 2018-08-23 at 5 31 00 pm" src="https://user-images.githubusercontent.com/1577872/44558690-6ddc7780-a6fa-11e8-8107-faa50512819d.png">

The gem log shows the following:
```
vienna:log jfoster$ tail -f *16303*
cmdLine= CONNECT AGENT
[Info]: RPC client/gem GCI levels = 865/865
[Info]: Client PID: 4948
[Info]: libssl-3.2.15-64.dylib: loaded
[Info]: User ID: SystemUser
[Info]: Repository: gs64stone1
[Info]: Session ID: 5
[Info]: GCI Client Host: ::ffff:192.168.2.133
[Info]: Page server PID: -1
[Info]: Login Time: 08/23/2018 17:23:10.072 PDT
```

**Comment by dalehenrich** [comment] 2018-08-24 00:40
so you are not able to reproduce the stack?

**Comment by jgfoster** [comment] 2018-08-24 00:46
The test fails earlier now:
```
5:45:37 PM, Thursday, August 23, 2018: 'Resource JadeiteTestResource could not be initialized'
TestResult class>>signalErrorWith:
JadeiteTestResource class>>signalInitializationError
[] in TestSuite>>run
Set>>do:
TestSuite>>run
[] in UnitTestPlugin>>runSuite:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
UnitTestPlugin>>runSuite:
UnitTestPlugin>>runTests
Symbol>>forwardTo:
CommandDescription>>performAgainst:
[] in Command>>value
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
Command>>value
ShellView>>performCommand:
IdeaSpaceShell(Shell)>>performCommand:
CommandQuery>>perform
DelegatingCommandPolicy(CommandPolicy)>>route:
[] in PushButton(View)>>onCommand:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
Cursor>>showWhile:
PushButton(View)>>onCommand:
PushButton(CommandButton)>>onActionPerformed
PushButton(View)>>performAction
PushButton>>command:id:
ContainerView(View)>>wmCommand:wParam:lParam:
ContainerView(View)>>dispatchMessage:wParam:lParam:
[] in InputState>>wndProc:message:wParam:lParam:cookie:
BlockClosure>>ifCurtailed:
InputState>>wndProc:message:wParam:lParam:cookie:
PushButton(ControlView)>>defaultWindowProcessing:wParam:lParam:
MouseEvent(WindowsEvent)>>defaultWindowProcessing
PushButton(View)>>onLeftButtonReleased:
PushButton(View)>>wmLButtonUp:wParam:lParam:
PushButton(View)>>dispatchMessage:wParam:lParam:
[] in InputState>>wndProc:message:wParam:lParam:cookie:
BlockClosure>>ifCurtailed:
InputState>>wndProc:message:wParam:lParam:cookie:
ShellView(View)>>isDialogMessage:
ShellView>>preTranslateMouseInput:
ShellView(View)>>preTranslateMessage:
InputState>>preTranslateMessage:
InputState>>pumpMessage:
InputState>>loopWhile:
InputState>>mainLoop
[] in InputState>>forkMain
ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry
```

**Comment by jgfoster** [comment] 2018-08-24 00:56
Same as above with most recent Jadite (cc37422b8dcf527b6cd7813a934752e800aaebe3) and Rowan (233a796888cbd25ea256bb7c4c8da7039b29403f).

**Comment by dalehenrich** [comment] 2018-08-24 00:58
okay ... [but this stack](https://github.com/ericwinger/Jade/issues/73#issuecomment-414897711) seems to be a simple attempt to load RowanSample1 from a workspace or perhaps the `project list`? 

I wasn't there when you produced [the stack](https://github.com/ericwinger/Jade/issues/73#issuecomment-414897711), but I just want to get a bit more information from stack ... the readlink: call on the stack is pretty diagnostic ... [It's going to somewhat painful to replace the `readlink -f`call and get the same behavior](https://github.com/AsymLabs/realpath-lib/blob/master/realpath-lib), but it is a bullet that has got to be bitten ...

**Comment by jgfoster** [comment] 2018-08-24 01:09
The original stack was a result of trying to run the test. Unfortunately, now that things are broken earlier we no longer have a ```readlink``` call on the stack. 

My workflow is to start with a new extent0.dbf and run the following script:
```
export ROWAN_PROJECTS_HOME=/Users/jfoster
stopnetldi
startnetldi -g -a jfoster -l /Users/jfoster/Library/GemStone/db4/log/netldi1.log
topaz -l << EOF
logout
errorCount
output push Rowan.out only
input $ROWAN_PROJECTS_HOME/Rowan/platforms/gemstone/topaz/3.2.15/install.tpz
output pop
errorCount
EOF
```
Is there something else I should do to "Rowanize" a new repository? Can you run the original test in a repository freshly Rowanized using only the above script?

**Comment by dalehenrich** [comment] 2018-08-24 01:34
I am not involved in getting this particular test run ... I am only involved because an error was reported while trying to clone a repository and the only stack that was provided was the one above ... I wanted more information from the stack with readlink: ... I know that readlink is a problem on mac and the solution is ugly, but there are not any good alternatives ... I would think that you would be unable to simply try to load the RowanSample1 example using the `projet list` but if that is too complicated for you to try, then that is okay ... also I'm not sure why you want me to run a test that fails for you in a different place than the one I am interested in ... I will now stop posting on this issue and quietly pursue the bug that I see with readlink: ... and let you and eric figure out why your tests don't run

**Comment by ericwinger** [comment] 2018-08-24 01:46
@jgfoster The JadeiteProjects test case now needs the RowanSample1 class available in several tests. So I added that to the test resource. I tried two different ways of doing it - I'm not happy with either of them but it was working for me when I checked in.

**Comment by dalehenrich** [comment] 2018-08-24 02:18
@ericwinger Why don't we sit down tomorrow(?) and I'll help you with the repository cloning issue ... which is independent of the mac clone issue ... if you want ...

**Comment by jgfoster** [comment] 2018-08-24 02:42
@ericwinger, When you say "it was working for me when I checked in," was that with an upgraded repository that already had extra things loaded (like RowanSample1), or was it with a brand new repository in which only Rowan was loaded?

**Comment by dalehenrich** [comment] 2018-08-24 02:59
@jgfoster just to be clear ... the readLink bug is a mac only bug (dalehenrich/Rowan#344) ... you are running tests on a mac and eric is running tests on linux, so you **will** see different behavior for tests that are cloning or reusing existing repos ... I will (hopefully) have a fix for this bug (dalehenrich/Rowan#344) tomorrow sometime ...

**Comment by ericwinger** [comment] 2018-08-24 14:36
> @ericwinger Why don't we sit down tomorrow(?) and I'll help you with the repository cloning issue ... which is independent of the mac clone issue ... if you want ...

Yes, let's.

**Comment by ericwinger** [comment] 2019-02-19 21:55
Reassigning to @LisaAlmarode in hopes she can figure out what, if anything, is left to do on this issue.

**Comment by ericwinger** [comment] 2019-07-17 16:16
@LisaAlmarode - I believe this bug can be closed. Can you see any open issues still remaining?

**Comment by LisaAlmarode** [comment] 2019-08-01 19:29
Very old bug; much has changed.

**Closed by LisaAlmarode** 2019-08-01 19:29 UTC
