### ISSUE TITLE
Hierarchy view empty if class not selected

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Jadeite#125] opened 2018-08-29 18:10 UTC
This may not be a bug, but it's kind of misleading API if this is intentional.

In 3.0.22, the only time I see the hierarchy tab not blank, is if I first am on the class tab and select a class.  In that case, if I go to the hierarchy tab it shows me that class's hierarchy view.  

The tab make it seem like these are alternate ways to look at the list of classes in the package, rather than the hierachy tab being a view for that class only... that sort of thing would make more sense on the lower half.

**Comment by ericwinger** [comment] 2018-08-31 21:38
What you are seeing is by design. I wasn't sure what the default hierarchy view should look like so I left it blank. Essentially, you click on a class, then go to it's hierarchy. Otherwise the hierarchy view is blank. 

However, I've got a potential improvement for this in Oscar3.0.25.  It shows the top level Object class and it's peers. My concern all along has been that it would be too slow. However, I did a little bit of tuning and I can bring up the formerly-blank hierarchy view in under 2 seconds. 

This will be checked in for 3.0.25. Please review and let me know what you think. I can take back out if need be.

**Comment by LisaAlmarode** [comment] 2018-09-03 21:37
On the whole, I think you should back out the change. I don't see that it helps, since it's not really a practical way to find a class.  It's not super-slow, but you don't get anything really useful to justify looking at that dialog.

**Comment by ericwinger** [comment] 2018-09-04 14:51
@LisaAlmarode Had another idea that wouldn't involve Object. If there's no selection in the class list and the hierarchy tab was clicked, what if we selected the first class in the class list and displayed that hierarchy? It's relatively zippy and gives you something less disconcerting than a blank list. 

I'll check that into 3.0.28 for your review.

**Comment by dalehenrich** [comment] 2018-09-04 14:56
In Pharo (at least older views) and tODE, only the classes in the list are displayed in hierarchy order ... then you get tos the relationship of the classes in the list ... I’ve a method (or 2) with the algorithm lying around if you are interested

**Comment by ericwinger** [comment] 2018-09-10 14:08
@dalehenrich  Can you point me at the methods with the algorithm for computing the hierarchy of just the listed classes that you mentioned? https://github.com/GemTalk/Jadeite/issues/125#issuecomment-418399044

**Comment by ericwinger** [comment] 2018-09-10 21:14
Fix in 3.0.32 for Lisa to review incorporates Dale's recommendation.

**Closed by ericwinger** 2018-09-10 21:14 UTC

**Comment by LisaAlmarode** [comment] 2018-09-12 18:39
I like this new behavior.
